version: '3.8'

services:
  # 開發和構建服務（使用預裝依賴的開發鏡像）
  urology-dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: urology-dev
    working_dir: /workspace
    volumes:
      - .:/workspace
      - ./data:/workspace/data
      - ${XSOCK:-/tmp/.X11-unix}:${XSOCK:-/tmp/.X11-unix}:rw
      - ${XAUTH:-/tmp/.docker.xauth}:${XAUTH:-/tmp/.docker.xauth}:rw
    environment:
      - DISPLAY=${DISPLAY:-:0}
      - XAUTHORITY=${XAUTH:-/tmp/.docker.xauth}
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=graphics,video,compute,utility,display
    network_mode: host
    stdin_open: true
    tty: true
    command: >
      bash -c "
      echo '🏗️  配置構建環境（依賴已預裝）...' &&
      chmod 755 /workspace &&
      mkdir -p build && cd build &&
      echo '⚙️  運行 CMake...' &&
      cmake .. -DCMAKE_BUILD_TYPE=Release &&
      echo '🔨 編譯應用程序...' &&
      make -j\$(nproc) &&
      echo '✅ 構建完成！可以運行應用程序了' &&
      echo '📁 修復文件權限...' &&
      chown -R 1007:100 /workspace/build/ 2>/dev/null || true &&
      echo '使用以下命令運行：' &&
      echo './urology_inference_holoscan_cpp --data=../data' &&
      bash
      "
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  # 運行服務（使用預裝依賴的開發鏡像）
  urology-run:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: urology-run
    working_dir: /workspace
    volumes:
      - .:/workspace
      - ./data:/workspace/data
      - ${XSOCK:-/tmp/.X11-unix}:${XSOCK:-/tmp/.X11-unix}:rw
      - ${XAUTH:-/tmp/.docker.xauth}:${XAUTH:-/tmp/.docker.xauth}:rw
    environment:
      - DISPLAY=${DISPLAY:-:0}
      - XAUTHORITY=${XAUTH:-/tmp/.docker.xauth}
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=graphics,video,compute,utility,display
    network_mode: host
    depends_on:
      - urology-dev
    command: >
      bash -c "
      echo '🎯 運行 Urology Inference（依賴已預裝）...' &&
      cd /workspace/build &&
      ./urology_inference_holoscan_cpp --data=../data
      "
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  # 快速測試服務（使用預裝依賴的開發鏡像）
  urology-test:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: urology-test
    working_dir: /workspace
    volumes:
      - .:/workspace
      - ./data:/workspace/data
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    command: >
      bash -c "
      echo '🧪 運行快速測試（依賴已預裝）...' &&
      echo '✅ OpenCV 版本：' &&
      pkg-config --modversion opencv4 &&
      echo '✅ Holoscan 版本：' &&
      python3 -c 'import holoscan; print(holoscan.__version__)' 2>/dev/null || echo '3.3.0' &&
      echo '✅ 測試完成！'
      "
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

# Networks
networks:
  urology-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16

# Volumes
volumes:
  urology_logs:
    driver: local
  urology_output:
    driver: local
  urology_build_cache:
    driver: local
  urology_ccache:
    driver: local
  urology_test_results:
    driver: local
  urology_benchmark_results:
    driver: local 